In [1]:
import numpy as np
from tornado.gen import multi

In [3]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(4,)


In [4]:
print(arr2.shape)

(2, 4)


In [5]:
arr3 = np.array([[1, 2, 3, 4]])
print(arr3.shape)

(1, 4)


In [6]:
print(arr.size)
print(arr2.size)

4
8


In [7]:
arr4 = np.array(5)
print(arr4.shape)

()


In [8]:
arr5 = np.array([[[1, 2, 3, 4]]])
print(arr5.shape)

(1, 1, 4)


In [9]:
print(arr.dtype)
print(arr2.dtype)

int64
int64


In [10]:
zeros_array = np.zeros((2, 3))
print(zeros_array.shape)
print(zeros_array)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
rng_arr = np.arange(10)
rng_arr2 = np.arange(2, 10)
rng_arr3 = np.arange(2, 10, 2)

In [12]:
print(rng_arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(rng_arr2)

[2 3 4 5 6 7 8 9]


In [14]:
print(rng_arr3)

[2 4 6 8]


In [15]:
print(type(rng_arr))

<class 'numpy.ndarray'>


In [16]:
arr = np.random.rand()
arr1 = np.random.rand(5)
arr2 = np.random.rand(2, 3)
arr3 = np.random.rand(2, 3, 2)

In [17]:
print(arr)

0.5621226904999649


In [18]:
print(arr1)

[0.31471501 0.94608476 0.10050754 0.9265967  0.01767236]


In [19]:
print(arr2)

[[0.56524485 0.06318013 0.26124923]
 [0.39125255 0.81530131 0.13377836]]


In [20]:
print(arr3)

[[[0.61450063 0.32938904]
  [0.31117514 0.05824851]
  [0.21357279 0.24831652]]

 [[0.49313242 0.87395587]
  [0.65333153 0.90115873]
  [0.92956755 0.81406744]]]


In [21]:
print(type(arr3))

<class 'numpy.ndarray'>


In [22]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
print(arr3[1, 1, 2])

12


In [24]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = np.array([9, 10, 11, 12, 13, 14, 15, 16])

sum_arr = arr1 + arr2
sub_arr = arr2 - arr1
multi_arr = arr1 * arr2

In [25]:
print(sum_arr)

[10 12 14 16 18 20 22 24]


In [26]:
print(sub_arr)

[8 8 8 8 8 8 8 8]


In [27]:
print(multi_arr)

[  9  20  33  48  65  84 105 128]


In [31]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
np.mean(arr)

np.float64(45.0)

In [32]:
np.median(arr)

np.float64(45.0)

In [33]:
np.std(arr)

np.float64(22.9128784747792)

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [39]:
arr = arr.reshape((2, 4))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [40]:
arr = arr.reshape((2, 2, 2))
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
arr = arr.reshape(2, 4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [46]:
arr = arr.transpose()
arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])